DD4J-1089 Add ASiC-S parsing, validating, and timestamping tests
naare/dd4jTestDemo pull request #2
Opened 2024-10-24 13:21 UTC by Sedemicra

2024-10-25 18:04 UTC, heititobi requested changes
Testimismõtted ei ole käesoleva PR-i skoop ja võib kaardistada eraldi pileti(te) all ning enne realiseerimist üle vaadata, mis neist on juba ühiktestidega kaetud.

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +//                .withDataFile("src/test/resources/files/Test_ASICS.asics", "application/vnd.etsi.asic-s+zip")
Taotuslikult sisse jäetud?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +                .withDataFile("src/test/resources/files/test.txt", "text/plain")
Kas mimetype on konteineri loomisel kohustuslik või toimub ka mingit sorti automaatne tuvastamine?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +        // Validate container
Esmased testimismõtted:
* Andmefaili mimetype on õige (kui peaks olema võimalik lasta automaatselt määrata, siis ka)? 
* Loodud ASIC-S konteineri mimetype on õige?
* Konteineri struktuur on õige?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +    void createCompositeAsicsAndValidate() {
Esmased testimismõtted:
* Erinevat tüüpi kapseldatud konteinerite korral raportis välimised/sisemised allkirjad/ajatemplid olemas?
* Millised konteinerid sobivad komposiitseteks ja tuleb viga, kui ei sobi? Mis juhtub nt. PDF või WORD dokumendi korral? 
* Allkirjade/templite vead/hoiatused raportis olemas?
* Vigase struktuuriga konteineri valideerimisel viga?
* Olemasoleva komposiitkonteineri avamine ja valideerimine toimetab ootuspäraselt?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +        // Validate container
Esmased testimismõtted:
* Struktuur vastab ootustele
* Mimetype-d vastavad ootustele

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +        assertEquals(1, result.getTimestampReports().size());
Sportlikust huvist, kas muidu kuidagi on võimalik kindlaks teha ajatempli kuuluvus sisemise/välimise konteineri  juurde?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +                .withDataFile("src/test/resources/files/test.txt", "text/plain")
Esmased testimismõtted:
* Vale mimetype -> ei kirjutata teegis üle ja ei põhjusta valideerimisel hoiatusi/vigu?
* Mitu andmefaili -> ASIC-S´is ei ole lubatud ja annab vea?
* Tühi andmefail -> Ei ole lubatud? 
** Tühja andmefailiga ASIC-S´i ajatembeldamine ei ole lubatud?
** Tühja andmefailiga konteinerit sisaldava ASIC-S valideerimisel tuleb sellekohane viga?
* Eesti ökosüsteemis arvatavasti on enamkasutatavad andmefailid DDOC, BDOC, ASIC-S ja ASIC-E konteinerid - on lubatud?

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTimestampTest.java
> +        assertTrue(result.getErrors().get(0).getMessage().contains("The certificate chain for time-stamp is not trusted, it does not contain a trust anchor."));
Need veateated viitavad, et sertifikaat ei ole usaldusnimekirjas (TSL) usaldatud.
Siin on vaja valideerida PROD režiimis. Nimelt kasutades konteinerit, kus allkiri/ajatempel on antud LIVE sertidega, tuleb kasutada ka LIVE usaldusnimekirju, mis laetakse ainult PROD režiimis. 
Seda saab alati kontrollida ka, kui vaadata TSL-i, kas seal on antud sert/välja andja sert usaldatud:
- Eesti TEST TSL https://open-eid.github.io/test-TL/EE_T.xml
- Eesti PROD TSL https://sr.riik.ee/tsl/estonian-tsl.xml

2024-10-25 18:04 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTimestampTest.java
> +        // Validate container
Esmased testimistmõtted:
* Valideerida konteineri struktuuri (ASiCArchiveManifest.xml olemasolu)
* ASiCArchiveManifest.xml sisu valideerida (k.a. mimetype reeglid)
* Mitmekordsel ajatembeldamisel nimetatakse ASiCArchiveManifest.xml faile ümber - valideerida, et see toimiks ootuspäraselt.

2024-10-29 09:33 UTC, Sedemicra reviewed
Vaatasin testimismõtted kergelt üle. Ehk mitte 100%, aga suuresti on ideed ühel või teisel kujul käsitsi läbi käidud. Panen eraldi piletisse, et vaadata, mis on ühiktesti tasandil kaetud, mis tuleks ühiktesti tasandil lisaks katta, ja kui saab selguse integratsioonitestide osas, mis jääb sinna lisamiseks.

2024-10-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/asics/AsicsTest.java
> +                .withDataFile("src/test/resources/files/test.txt", "text/plain")
Mulle teadaolevalt on mimetype konteineri loomisel kohustuslik.

2024-10-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/asics/AsicsTest.java
> +//                .withDataFile("src/test/resources/files/Test_ASICS.asics", "application/vnd.etsi.asic-s+zip")
Jah

2024-10-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/asics/AsicsTest.java
> +        assertEquals(1, result.getTimestampReports().size());
Jah. Konkreetne näide: 
`nestedContainer.getTimestamps()` tagastab kapseldatud konteineri ajatemplid. 
`container.getTimestamps()` tagastab kapseldava konteineri ajatemplid.
Valideerimiseks saaks kasutada: `assertEquals(nestedContainer.getTimestamps().get(0).getUniqueId(), result.getTimestampReports().get(0).getUniqueId());`

2024-10-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/asics/AsicsTimestampTest.java
> +        assertTrue(result.getErrors().get(0).getMessage().contains("The certificate chain for time-stamp is not trusted, it does not contain a trust anchor."));
Hea tähelepanek. See aspekt jäi kahe silma vahele. 
Hetkel panin selle testi confi PROD režiimi ja kohendasin validatsioone.

2024-10-29 11:10 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +        assertEquals(1, result.getTimestampReports().size());
Kui veel ei ole lisatud, siis võib antud mõtte panna testimismõtete pileti alla kirja.

2024-10-29 11:32 UTC, heititobi commented on src/test/java/org/naare/asics/AsicsTest.java
> +        assertEquals(1, result.getTimestampReports().size());
Ahhaa, testimisel saab tõesti nii. 
Ma rohkem mõtlesin, et kas DD4J raportis on ka kuidagi ajatemplid eristatavad või mitte?

Testimismõtetele lisaks juurde:
* Mitmetasandiselt kapseldatud (ASIC-S´s on ASIC-S, milles on ASIC-E/DDOC/BDOC) konteineri valideerimisel tagastatakse ainult esimese tasandi info.
* Milliste konteineritüüpide valideerimisel ajatemplite tagastamise meetod midagi tagastab.
* Ajatemplite puudumisel tagastatakse tühi loend?

2024-10-29 15:34 UTC, heititobi approved these changes

2024-10-30 07:33 UTC, merged