1077 Add OCSP source tests
naare/dd4jTestDemo pull request #5
Opened 2024-11-27 14:32 UTC by Sedemicra

2024-11-28 15:54 UTC, heititobi requested changes

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +        PKCS12SignatureToken signatureToken = getDefaultPkcs12SignatureToken("1234");
Helpers alla tegid allkirjastamise abimeetodi SignPkcs12. Äkki kasutada seda.

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +    void extendTToLTFail() {
Siin võiks testi nimetuses täpsustada, et tegu käitumisega CustomOcspSource vaikeväärtuse korral.

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +    void extendLTToLTAPass() {
camelCase korral LT -> Lt ja LTA -> Lta

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
SignatureExtensionTest.java klass kordab siin olevaid teste - võiks üle vaadata, kus mida vaja on.

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +        PKCS12SignatureToken signatureToken = getDefaultPkcs12SignatureToken("1234");
Äkki kasutada PKCS12 abimeetodit.

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +    @Disabled
Võiks selle testi vajaduse üle vaadata. 
Üldiselt ei ole pannud PKCS11 asjadele Disabled, et oleks lihtsam regressioontestimisel ID-kaart lugejasse torgata ja kõik testid läbi lasta.

2024-11-28 15:54 UTC, heititobi commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +    void signLTWithSigningOcspSourceDefaultPasses() {
See arvatavasti kordab mõnda testi SignatureCreationTest.java klassis (nt. signPkcs12WithDataToSign).

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +    void signLTWithSigningOcspSourceDefaultPasses() {
On kaetud signWithAllowedProfile testiga - eemaldasin siinse duplikaadi.

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +        PKCS12SignatureToken signatureToken = getDefaultPkcs12SignatureToken("1234");
Võtsin abimeetodi kasutusele.

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +    void extendLTToLTAPass() {
Muudetud

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +    void extendTToLTFail() {
Liigutasin teste veidi ümber, nii et see pole enam oluline.

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
> +        PKCS12SignatureToken signatureToken = getDefaultPkcs12SignatureToken("1234");
Võtsin kasutusele

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/extension/ExtensionOcspSourceTest.java
Refaktosin teste.

2024-11-29 09:33 UTC, Sedemicra commented on src/test/java/org/naare/signing/SignatureOcspSourceTest.java
> +    @Disabled
Sellisel kujul ei ole enam vajalik - eemaldasin.

2024-11-29 15:41 UTC, heititobi approved these changes

2024-11-29 15:41 UTC, merged